import React from 'react';
import { Share2, Check, X } from 'lucide-react';

interface ShareInsightModalProps {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  insight: string;
}

export const ShareInsightModal: React.FC<ShareInsightModalProps> = ({ isOpen, onClose, title, insight }) => {
  const [copied, setCopied] = React.useState(false);

  if (!isOpen) return null;

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(`${title}\n\n${insight}\n\nGenerated by @FinpluseAI`);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy text: ', err);
    }
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={onClose} />
      <div className="relative w-full max-w-md bg-[#0a0a0a] border border-white/[0.08] rounded-2xl p-6 shadow-2xl">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-[#a1a1aa] hover:text-white transition-colors"
        >
          <X className="w-5 h-5" />
        </button>
        
        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 rounded-full bg-blue-500/10 flex items-center justify-center">
            <Share2 className="w-5 h-5 text-blue-400" />
          </div>
          <h2 className="text-xl font-medium text-white">Share Milestone</h2>
        </div>

        <div className="bg-[#141414] border border-white/[0.04] rounded-xl p-4 mb-6 relative overflow-hidden group">
          <div className="absolute top-0 right-0 w-32 h-32 bg-blue-500/5 blur-[40px] rounded-full pointer-events-none" />
          <h3 className="text-sm font-medium text-white mb-2">{title}</h3>
          <p className="text-[#a1a1aa] text-sm leading-relaxed">{insight}</p>
          <div className="mt-4 flex items-center gap-2">
            <div className="w-4 h-4 rounded-sm bg-white flex items-center justify-center">
              <span className="text-[10px] font-bold text-black">F</span>
            </div>
            <span className="text-xs text-[#52525b]">Finpluse AI</span>
          </div>
        </div>

        <button
          onClick={handleCopy}
          className="w-full flex items-center justify-center gap-2 bg-white text-black py-3 rounded-xl text-sm font-medium hover:bg-[#e5e5e5] transition-all active:scale-[0.98]"
        >
          {copied ? (
            <>
              <Check className="w-4 h-4" />
              Copied to clipboard
            </>
          ) : (
            <>
              <Share2 className="w-4 h-4" />
              Copy to Share
            </>
          )}
        </button>
      </div>
    </div>
  );
};
